### ISSUE TITLE
Cleanup after ImpressCMS install

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/vagrant-impressbox#12]
Quite simply : 
- remove the install folder
- make the mainfile.php read-only

**Comment by MekDrop** [comment]
I'm just curious why do you need such things for development boxes? I see at least few problems this will rise. Because Impressbox is use latest Git repo code for website not release install.

**Comment by MekDrop** [comment]
I think we need to implement possibility to install @ImpressCMS from command line first. Without such functionality I'm not sure how to add here any useful deployment options.

**Comment by fiammybe** [comment]
I agree. Installing is a first step, but a goal would be to arrive at a
similar functionality set as Drush (www.drush.org)  does for Drupal

Op do 30 jun. 2016 om 15:25 schreef Raimondas Rimkevičius <
notifications@github.com>:

**Comment by MekDrop** [comment]
Yeah I agree! But I think that functionality is linked more with @ImpressCMS but not with this plug-in. We need improve there command line experience.

**Comment by fiammybe** [comment]
totally correect. We need to have a command line experience in ImpressCMS.
Your Imp script in 2.0 will be the first step I think. ;-)

Op ma 11 jul. 2016 om 09:55 schreef Raimondas Rimkevičius <
notifications@github.com>:

**Comment by MekDrop** [comment]
This will be solved after implementing #22 for any possible CMS. So closing this one.
